"""empty message

Revision ID: 9964e5dda663
Revises: 11dc0d75a426
Create Date: 2025-01-29 23:07:22.314630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9964e5dda663'
down_revision = '11dc0d75a426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
         batch_op.add_column(sa.Column('cover_image', sa.String(length=200), nullable=True))  # Allow NULL values
         batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False)))
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
